### ISSUE TITLE
"Blank" screen with VCMI 1.2

### ISSUE THREAD

**Issue by Laserlicht** [flathub/eu.vcmi.VCMI#122]
This screen after selecting Single Player -> Single Scenario
![grafik](https://user-images.githubusercontent.com/13953785/232636663-27cf3e30-ed37-4ea0-bf72-85b592da024d.png)

Campaign also doesn't work.

Tested two different devices.

**Comment by juml** [comment]
same issue (fedora).
vcmiserver crash, some boost lib symbols in trace.

**Comment by pcercuei** [comment]
Same issue on Debian.

**Comment by Alexander-Wilms** [comment]
Reverted vcmi to version 1.1.1 for now
