### ISSUE TITLE
Wrong checksum, can't update

### ISSUE THREAD

**Issue by ToRRent1812** [flathub/eu.vcmi.VCMI#155]
Typing flatpak update -y gives me this error

app/eu.vcmi.VCMI/x86_64/stable from repository flathub: opcode close: Corrupted file object; checksum expected='a258574c46154aee3dec5a19f94a867cbc387468a3ed71a6434a035fcdd2c667' actual='1422ffe15e3042399dd41bf1ef3c0642ac4e8a012c0c6c378851bd90fc0ea0c4'

I can't update to 1.4.4

**Comment by ToRRent1812** [comment]
I've managed to fix the issue by removing the app and installing again.

**Comment by Alexander-Wilms** [comment]
Seems like that was a random issue with Flatpak and not related to the package itself.
